CREATE DATABASE IF NOT EXISTS wefunder

CREATE TABLE users (
	user_id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(64) NOT NULL
) ENGINE=INNODB;

CREATE TABLE matches (
	match_id INT AUTO_INCREMENT PRIMARY KEY,
	user_1_id INT NOT NULL,
	user_2_id INT NOT NULL,
	winner_id INT NOT NULL,
	round_id INT NOT NULL
) ENGINE=INNODB;

CREATE TABLE rounds (
	round_id INT AUTO_INCREMENT PRIMARY KEY,
	single_elimination BOOLEAN NOT NULL DEFAULT TRUE
)ENGINE=INNODB;